export const cars = [
  {
    brand: 'Opel',
    model: 'Corsa',
    generation: 'A',
    bodyStyle: '3-door hatchback, 5-door hatchback',
    country: 'Germany',
    yearStart: '1982',
    yearEnd: '1993',
    engine: '1.0L–1.6L petrol, 1.5L diesel',
    horsepower: '45–100 hp',
    design: 'Boxy and compact with flared arches',
    notes:
      'The first Corsa marked Opel’s entry into the small car market. It was affordable, reliable, and easy to maintain — quickly becoming a favorite across Europe.',
    img: 'https://cars-database-ovrv.onrender.com/images/opel-corsa-a.jpg',
  },
  {
    brand: 'Opel',
    model: 'Corsa',
    generation: 'B',
    bodyStyle: '3-door hatchback, 5-door hatchback',
    country: 'Germany',
    yearStart: '1993',
    yearEnd: '2000',
    engine: '1.0L–1.6L petrol, 1.5L–1.7L diesel',
    horsepower: '50–106 hp',
    design: 'More rounded with smoother lines, improved aerodynamics',
    notes:
      'The second generation introduced airbags and catalytic converters as standard. It was also the first Corsa to feature a six-speed transmission (in the GSI model).',
    img: 'https://cars-database-ovrv.onrender.com/images/opel-corsa-b.jpg',
  },
  {
    brand: 'Opel',
    model: 'Corsa',
    generation: 'C',
    bodyStyle: '3-door hatchback, 5-door hatchback',
    country: 'Germany',
    yearStart: '2000',
    yearEnd: '2006',
    engine: '1.0L–1.8L petrol, 1.3L–1.7L diesel',
    horsepower: '60–125 hp',
    design: 'Modern, curvy design with a more aggressive front end',
    notes:
      'This generation introduced the sporty Corsa OPC variant with a 1.8L turbo engine. It featured improved safety and interior quality over previous models.',
    img: 'https://cars-database-ovrv.onrender.com/images/opel-corsa-c.jpg',
  },
  {
    brand: 'Opel',
    model: 'Corsa',
    generation: 'D',
    bodyStyle: '3-door hatchback, 5-door hatchback',
    country: 'Germany',
    yearStart: '2006',
    yearEnd: '2014',
    engine: '1.0L–1.6L petrol, 1.3L–1.7L diesel',
    horsepower: '60–192 hp',
    design: 'Sleek, dynamic styling with a prominent grille and sharp lines',
    notes:
      'The Corsa D was larger and more refined, with improved handling. The OPC version produced 192 hp, making it the most powerful Corsa yet.',
    img: 'https://cars-database-ovrv.onrender.com/images/opel-corsa-d.jpg',
  },
  {
    brand: 'Opel',
    model: 'Corsa',
    generation: 'E',
    bodyStyle: '3-door hatchback, 5-door hatchback',
    country: 'Germany',
    yearStart: '2014',
    yearEnd: '2019',
    engine: '1.0L–1.4L petrol, 1.3L–1.7L diesel',
    horsepower: '75–150 hp',
    design: 'Sharper, more angular styling with LED daytime running lights',
    notes:
      'This generation introduced advanced tech like IntelliLink infotainment. The OPC version had a 1.6L turbo with 207 hp, the fastest Corsa ever.',
    img: 'https://cars-database-ovrv.onrender.com/images/opel-corsa-e.jpg',
  },
  {
    brand: 'Opel',
    model: 'Corsa',
    generation: 'F',
    bodyStyle: '5-door hatchback',
    country: 'Germany',
    yearStart: '2019',
    yearEnd: 'present',
    engine: '1.2L–1.4L petrol, 1.5L diesel, electric (Corsa-e)',
    horsepower: '75–136 hp (petrol), 100 hp (electric)',
    design:
      'Modern, aggressive look with a floating roof option and slim headlights',
    notes:
      'The first Corsa to offer a fully electric version (Corsa-e). Based on a PSA platform (Peugeot 208), it features advanced driver aids and a digital cockpit.',
    img: 'https://cars-database-ovrv.onrender.com/images/opel-corsa-f.jpeg',
  },
  {
    brand: 'Audi',
    model: 'A5',
    generation: '8T',
    bodyStyle: 'Coupe, Cabriolet, Sportback',
    country: 'Germany',
    yearStart: '2007',
    yearEnd: '2016',
    engine: '1.8L TFSI, 2.0L TFSI, 3.2L FSI, 2.7L/3.0L TDI, 4.2L V8 (RS5)',
    horsepower: '120–450 hp',
    design:
      'Elegant, flowing lines with a wide grille and LED daytime running lights (facelift)',
    notes:
      'The first-gen A5 introduced the sleek Coupe and later the five-door Sportback (2010). The RS5 (2010) featured a 4.2L V8 with 450 hp.',
    img: 'https://cars-database-ovrv.onrender.com/images/audi-a5-b8.jpg',
  },
  {
    brand: 'Audi',
    model: 'A5',
    generation: 'F5',
    bodyStyle: 'Coupe, Cabriolet, Sportback',
    country: 'Germany',
    yearStart: '2016',
    yearEnd: '2023',
    engine:
      '1.4L TFSI, 2.0L TFSI, 3.0L TFSI, 2.0L TDI, 3.0L TDI, 2.9L TFSI (RS5)',
    horsepower: '150–450 hp',
    design:
      'Sharper edges, hexagonal grille, Matrix LED headlights, and a more aggressive stance',
    notes:
      'The second-gen A5 featured a lighter MLB Evo platform, improved tech (Virtual Cockpit), and a twin-turbo 2.9L V6 in the RS5 (2017).',
    img: 'https://cars-database-ovrv.onrender.com/images/audi-a5-b9.jpeg',
  },
  {
    brand: 'Audi',
    model: 'A5',
    generation: 'B10',
    bodyStyle: 'Coupe, Cabriolet, Sportback (expected)',
    country: 'Germany',
    yearStart: '2024 (expected)',
    yearEnd: 'TBA',
    engine:
      '2.0L TFSI, 3.0L TFSI, PHEV options, possible full-electric variant',
    horsepower: '200–500+ hp (estimated)',
    design:
      'Expected to follow Audi’s new design language with sharper lines and an EV-inspired grille',
    notes:
      'The next-gen A5 will likely switch to an updated platform (PPE for electric versions) and offer advanced autonomous driving features.',
    img: 'https://cars-database-ovrv.onrender.com/images/audi-a5-b10.jpg',
  },
  {
    brand: 'Audi',
    model: 'A7',
    generation: 'C7',
    bodyStyle: 'Sportback (5-door liftback)',
    country: 'Germany',
    yearStart: '2010',
    yearEnd: '2018',
    engine: '2.0L TFSI, 3.0L TFSI, 3.0L TDI, 4.0L TFSI (S7/RS7)',
    horsepower: '252–560 hp',
    design:
      'Sleek "four-door coupe" profile with a sloping roofline, LED lighting, and minimalist styling',
    notes:
      'The first A7 introduced Audi’s Sportback design, blending coupe aesthetics with practicality. The RS7 (2013) debuted with a 4.0L twin-turbo V8 (560 hp).',
    img: 'https://cars-database-ovrv.onrender.com/images/audi-a7-4g.jpg',
  },
  {
    brand: 'Audi',
    model: 'A7',
    generation: 'C8',
    bodyStyle: 'Sportback (5-door liftback)',
    country: 'Germany',
    yearStart: '2018',
    yearEnd: 'present',
    engine: '2.0L TFSI, 3.0L TFSI (mild-hybrid), 3.0L TDI, 4.0L TFSI (S7/RS7)',
    horsepower: '245–600 hp',
    design:
      'Sharper lines, wider grille, full-width OLED taillights, and a more aggressive stance',
    notes:
      'The second-gen A7 adopted Audi’s new design language and tech, including the MMI Touch Response system. The RS7 Performance (2020) pushed 600 hp.',
    img: 'https://cars-database-ovrv.onrender.com/images/audi-a7-4k.jpg',
  },
  {
    brand: 'Audi',
    model: 'A7',
    generation: 'C8 Facelift',
    bodyStyle: 'Sportback (5-door liftback)',
    country: 'Germany',
    yearStart: '2023',
    yearEnd: 'present',
    engine: '3.0L TFSI (mild-hybrid), 4.0L TFSI (S7/RS7)',
    horsepower: '340–630 hp',
    design:
      'Minor tweaks to grille and bumpers, updated Matrix LED headlights, and new wheel designs',
    notes:
      'The facelifted A7 refined the mild-hybrid system and added more standard tech. The RS7 gained a slight power bump (630 hp in the Performance trim).',
    img: 'https://cars-database-ovrv.onrender.com/images/audi-a7-4k8.jpg',
  },
  {
    brand: 'Ferrari',
    model: '812',
    generation: 'Superfast',
    bodyStyle: 'Berlinetta',
    country: 'Italy',
    yearStart: '2017',
    yearEnd: '2020',
    engine: '6.5L F140 GA V12',
    horsepower: '789 hp',
    design: 'Aggressive aerodynamics, sleek lines',
    notes:
      'Replaced the F12berlinetta; featured Ferrari’s most powerful production V12 at launch.',
    img: 'https://cars-database-ovrv.onrender.com/images/812-superfast.jpeg',
  },
  {
    brand: 'Ferrari',
    model: '812',
    generation: 'GTS',
    bodyStyle: 'Convertible',
    country: 'Italy',
    yearStart: '2019',
    yearEnd: '2023',
    engine: '6.5L F140 GA V12',
    horsepower: '789 hp',
    design: 'Retractable hardtop, reinforced chassis',
    notes: 'First front-engine V12 Ferrari convertible since the 365 GTS4.',
    img: 'https://cars-database-ovrv.onrender.com/images/812-gts.jpg',
  },
  {
    brand: 'Ferrari',
    model: '812',
    generation: 'Competizione',
    bodyStyle: 'Berlinetta',
    country: 'Italy',
    yearStart: '2021',
    yearEnd: '2023',
    engine: '6.5L F140 GC V12',
    horsepower: '819 hp',
    design: 'Vented hood, rear spoiler, Lexan rear window',
    notes: 'Limited to 999 units; track-focused variant with higher redline.',
    img: 'https://cars-database-ovrv.onrender.com/images/812-comp.jpg',
  },
  {
    brand: 'Ferrari',
    model: '812',
    generation: 'Competizione A',
    bodyStyle: 'Convertible',
    country: 'Italy',
    yearStart: '2021',
    yearEnd: '2023',
    engine: '6.5L F140 GC V12',
    horsepower: '819 hp',
    design: 'Removable carbon-fiber hardtop',
    notes: 'Convertible version of Competizione; limited to 599 units.',
    img: 'https://cars-database-ovrv.onrender.com/images/812-comp-a.jpg',
  },
  {
    brand: 'Lamborghini',
    model: 'Aventador',
    generation: 'LP-700',
    bodyStyle: 'Coupe',
    country: 'Italy',
    yearStart: '2011',
    yearEnd: '2016',
    engine: '6.5L L539 V12',
    horsepower: '700 hp',
    design: 'Angular wedge shape with scissor doors',
    notes:
      'Original Aventador that replaced the Murciélago. Featured carbon fiber monocoque chassis.',
    img: 'https://cars-database-ovrv.onrender.com/images/aventador-lp.jpeg',
  },
  {
    brand: 'Lamborghini',
    model: 'Aventador',
    generation: 'S',
    bodyStyle: 'Coupe/Roadster',
    country: 'Italy',
    yearStart: '2016',
    yearEnd: '2022',
    engine: '6.5L L539 V12',
    horsepower: '740 hp',
    design: 'Updated front bumper and rear diffuser',
    notes: 'Facelifted version with new electronics and improved aerodynamics.',
    img: 'https://cars-database-ovrv.onrender.com/images/aventador-s.jpeg',
  },
  {
    brand: 'Lamborghini',
    model: 'Aventador',
    generation: 'SVJ',
    bodyStyle: 'Coupe/Roadster',
    country: 'Italy',
    yearStart: '2018',
    yearEnd: '2022',
    engine: '6.5L L539 V12',
    horsepower: '770 hp',
    design: 'Extreme aerodynamics with ALA active wing system',
    notes:
      'Track-focused ultimate version that held Nürburgring production car record.',
    img: 'https://cars-database-ovrv.onrender.com/images/aventador-svj.jpeg',
  },
];
